[package]
name = "cover_tool"
version = "0.1.0"
authors = ["imaginary-upside <imaginary-upside@protonmail.ch>"]
edition = "2018"

[dependencies]
tide = "0.16.0"
serde = { version = "1.0", features = ["derive"] }
async-std = { version = "1.8.0", features = ["attributes"] }